order: 6
collated: true
variants:
- name: default
  context:
    label: Button
- name: secondary
  context:
    label: Secondary
    mods: ['secondary']
- name: disabled
  context:
    label: Disabled button
    disabled: true
- name: cancel
  context:
    label: Cancel
    href: /
    mods: [cancel]
- name: input
  context:
    label: Submit
    type: submit
- name: input previous
  context:
    label: Submit
    type: submit
    mods: [previous]
- name: input next
  context:
    label: Submit
    type: submit
    mods: [next]
- name: previous
  context:
    label: Previous
    mods: [previous]
- name: next
  context:
    label: Next
    mods: [next]
- name: link
  context:
    label: Link
    mods: [link]
- name: link previous
  context:
    label: Link
    mods: [link, previous]
- name: link next
  context:
    label: Link
    mods: [link, next]
- name: button
  context:
    label: Button
    mods: [stacked]
