collated: true
variants:
- name: radio yes
  context:
    label: 'Yes'
    value: 'yes'
    type: 'radio'
    mods: ['radio']
    id: 'input1-1'
    name: 'group1'
- name: radio no
  context:
    label: 'No'
    value: 'no'
    type: 'radio'
    mods: ['radio']
    id: 'input2-1'
    name: 'group1'
