//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS111.Integration.DOS.Api.DOSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", ConfigurationName="DOSService.PathWayServiceSoap")]
    public interface PathWayServiceSoap {
        
        // CODEGEN: Generating message contract since message ServiceDetailsByIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceDetailsById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse ServiceDetailsById(NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceDetailsById", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse> ServiceDetailsByIdAsync(NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest request);
        
        // CODEGEN: Generating message contract since message DispositionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/Dispositions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.DispositionsResponse Dispositions(NHS111.Integration.DOS.Api.DOSService.DispositionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/Dispositions", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.DispositionsResponse> DispositionsAsync(NHS111.Integration.DOS.Api.DOSService.DispositionsRequest request);
        
        // CODEGEN: Generating message contract since message CheckCapacityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/CheckCapacity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse CheckCapacity(NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/CheckCapacity", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse> CheckCapacityAsync(NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest request);
        
        // CODEGEN: Generating message contract since message CheckCapacitySummaryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/CheckCapacitySummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse CheckCapacitySummary(NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/CheckCapacitySummary", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse> CheckCapacitySummaryAsync(NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest request);
        
        // CODEGEN: Generating message contract since message ServiceCareRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceCare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse ServiceCare(NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceCare", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse> ServiceCareAsync(NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest request);
        
        // CODEGEN: Generating message contract since message ExceptionCaptureRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ExceptionCapture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse ExceptionCapture(NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ExceptionCapture", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse> ExceptionCaptureAsync(NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest request);
        
        // CODEGEN: Generating message contract since message ServiceCareExceptionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceCareException", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse ServiceCareException(NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceCareException", ReplyAction="*")]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse> ServiceCareExceptionAsync(NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string caseRefField;
        
        private int idField;
        
        private short exceptionidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string caseRef {
            get {
                return this.caseRefField;
            }
            set {
                this.caseRefField = value;
                this.RaisePropertyChanged("caseRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short exceptionid {
            get {
                return this.exceptionidField;
            }
            set {
                this.exceptionidField = value;
                this.RaisePropertyChanged("exceptionid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ExceptionCapture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int exceptionidField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int exceptionid {
            get {
                return this.exceptionidField;
            }
            set {
                this.exceptionidField = value;
                this.RaisePropertyChanged("exceptionid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string contactDetailsField;
        
        private string addressField;
        
        private string urlField;
        
        private string notesField;
        
        private bool obsoleteField;
        
        private System.DateTime updateTimeField;
        
        private bool openAllHoursField;
        
        private ServiceCareItemRotaSession[] rotaSessionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
                this.RaisePropertyChanged("contactDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool obsolete {
            get {
                return this.obsoleteField;
            }
            set {
                this.obsoleteField = value;
                this.RaisePropertyChanged("obsolete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
                this.RaisePropertyChanged("updateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool openAllHours {
            get {
                return this.openAllHoursField;
            }
            set {
                this.openAllHoursField = value;
                this.RaisePropertyChanged("openAllHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public ServiceCareItemRotaSession[] rotaSessions {
            get {
                return this.rotaSessionsField;
            }
            set {
                this.rotaSessionsField = value;
                this.RaisePropertyChanged("rotaSessions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareItemRotaSession : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DayOfWeek startDayOfWeekField;
        
        private TimeOfDay startTimeField;
        
        private DayOfWeek endDayOfWeekField;
        
        private TimeOfDay endTimeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DayOfWeek startDayOfWeek {
            get {
                return this.startDayOfWeekField;
            }
            set {
                this.startDayOfWeekField = value;
                this.RaisePropertyChanged("startDayOfWeek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeOfDay startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DayOfWeek endDayOfWeek {
            get {
                return this.endDayOfWeekField;
            }
            set {
                this.endDayOfWeekField = value;
                this.RaisePropertyChanged("endDayOfWeek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TimeOfDay endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum DayOfWeek {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class TimeOfDay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short hoursField;
        
        private short minutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("minutes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class serviceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareSummaryDestination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private Capacity capacityField;
        
        private string nameField;
        
        private string contactDetailsField;
        
        private string addressField;
        
        private string postcodeField;
        
        private int northingsField;
        
        private bool northingsFieldSpecified;
        
        private int eastingsField;
        
        private bool eastingsFieldSpecified;
        
        private string urlField;
        
        private string notesField;
        
        private bool obsoleteField;
        
        private System.DateTime updateTimeField;
        
        private bool openAllHoursField;
        
        private ServiceCareItemRotaSession[] rotaSessionsField;
        
        private serviceDetails serviceTypeField;
        
        private string odsCodeField;
        
        private serviceDetails rootParentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Capacity capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
                this.RaisePropertyChanged("capacity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
                this.RaisePropertyChanged("contactDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int northings {
            get {
                return this.northingsField;
            }
            set {
                this.northingsField = value;
                this.RaisePropertyChanged("northings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool northingsSpecified {
            get {
                return this.northingsFieldSpecified;
            }
            set {
                this.northingsFieldSpecified = value;
                this.RaisePropertyChanged("northingsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int eastings {
            get {
                return this.eastingsField;
            }
            set {
                this.eastingsField = value;
                this.RaisePropertyChanged("eastings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eastingsSpecified {
            get {
                return this.eastingsFieldSpecified;
            }
            set {
                this.eastingsFieldSpecified = value;
                this.RaisePropertyChanged("eastingsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool obsolete {
            get {
                return this.obsoleteField;
            }
            set {
                this.obsoleteField = value;
                this.RaisePropertyChanged("obsolete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime updateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
                this.RaisePropertyChanged("updateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool openAllHours {
            get {
                return this.openAllHoursField;
            }
            set {
                this.openAllHoursField = value;
                this.RaisePropertyChanged("openAllHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public ServiceCareItemRotaSession[] rotaSessions {
            get {
                return this.rotaSessionsField;
            }
            set {
                this.rotaSessionsField = value;
                this.RaisePropertyChanged("rotaSessions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public serviceDetails serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string odsCode {
            get {
                return this.odsCodeField;
            }
            set {
                this.odsCodeField = value;
                this.RaisePropertyChanged("odsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public serviceDetails rootParent {
            get {
                return this.rootParentField;
            }
            set {
                this.rootParentField = value;
                this.RaisePropertyChanged("rootParent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum Capacity {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareDestination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private Capacity capacityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Capacity capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
                this.RaisePropertyChanged("capacity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Case : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string caseRefField;
        
        private string caseIdField;
        
        private string postcodeField;
        
        private string surgeryField;
        
        private short ageField;
        
        private ageFormatType ageFormatField;
        
        private int dispositionField;
        
        private int symptomGroupField;
        
        private int[] symptomDiscriminatorListField;
        
        private int searchDistanceField;
        
        private bool searchDistanceFieldSpecified;
        
        private genderType genderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string caseRef {
            get {
                return this.caseRefField;
            }
            set {
                this.caseRefField = value;
                this.RaisePropertyChanged("caseRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string caseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("caseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string surgery {
            get {
                return this.surgeryField;
            }
            set {
                this.surgeryField = value;
                this.RaisePropertyChanged("surgery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ageFormatType ageFormat {
            get {
                return this.ageFormatField;
            }
            set {
                this.ageFormatField = value;
                this.RaisePropertyChanged("ageFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int disposition {
            get {
                return this.dispositionField;
            }
            set {
                this.dispositionField = value;
                this.RaisePropertyChanged("disposition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int symptomGroup {
            get {
                return this.symptomGroupField;
            }
            set {
                this.symptomGroupField = value;
                this.RaisePropertyChanged("symptomGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public int[] symptomDiscriminatorList {
            get {
                return this.symptomDiscriminatorListField;
            }
            set {
                this.symptomDiscriminatorListField = value;
                this.RaisePropertyChanged("symptomDiscriminatorList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int searchDistance {
            get {
                return this.searchDistanceField;
            }
            set {
                this.searchDistanceField = value;
                this.RaisePropertyChanged("searchDistance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchDistanceSpecified {
            get {
                return this.searchDistanceFieldSpecified;
            }
            set {
                this.searchDistanceFieldSpecified = value;
                this.RaisePropertyChanged("searchDistanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public genderType gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum ageFormatType {
        
        /// <remarks/>
        Years,
        
        /// <remarks/>
        AgeGroup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum genderType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Disposition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ContactDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private contactType tagField;
        
        private string nameField;
        
        private string valueField;
        
        private int orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public contactType tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum contactType {
        
        /// <remarks/>
        dts,
        
        /// <remarks/>
        itk,
        
        /// <remarks/>
        telno,
        
        /// <remarks/>
        email,
        
        /// <remarks/>
        faxno,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceDetailsById", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceDetailsByIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public string serviceId;
        
        public ServiceDetailsByIdRequest() {
        }
        
        public ServiceDetailsByIdRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, string serviceId) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.serviceId = serviceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceDetailsByIdResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceDetailsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.ContactDetail[] ContactDetails;
        
        public ServiceDetailsByIdResponse() {
        }
        
        public ServiceDetailsByIdResponse(NHS111.Integration.DOS.Api.DOSService.ContactDetail[] ContactDetails) {
            this.ContactDetails = ContactDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Dispositions", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class DispositionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        public DispositionsRequest() {
        }
        
        public DispositionsRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DispositionsResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class DispositionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.Disposition[] DispositionsResult;
        
        public DispositionsResponse() {
        }
        
        public DispositionsResponse(NHS111.Integration.DOS.Api.DOSService.Disposition[] DispositionsResult) {
            this.DispositionsResult = DispositionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacity", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public NHS111.Integration.DOS.Api.DOSService.Case c;
        
        public CheckCapacityRequest() {
        }
        
        public CheckCapacityRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacityResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareDestination[] CheckCapacityResult;
        
        public CheckCapacityResponse() {
        }
        
        public CheckCapacityResponse(NHS111.Integration.DOS.Api.DOSService.ServiceCareDestination[] CheckCapacityResult) {
            this.CheckCapacityResult = CheckCapacityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacitySummary", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacitySummaryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public NHS111.Integration.DOS.Api.DOSService.Case c;
        
        public CheckCapacitySummaryRequest() {
        }
        
        public CheckCapacitySummaryRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacitySummaryResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacitySummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareSummaryDestination[] CheckCapacitySummaryResult;
        
        public CheckCapacitySummaryResponse() {
        }
        
        public CheckCapacitySummaryResponse(NHS111.Integration.DOS.Api.DOSService.ServiceCareSummaryDestination[] CheckCapacitySummaryResult) {
            this.CheckCapacitySummaryResult = CheckCapacitySummaryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceCare", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceCareRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public int serviceCareId;
        
        public ServiceCareRequest() {
        }
        
        public ServiceCareRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, int serviceCareId) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.serviceCareId = serviceCareId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceCareResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceCareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareItem ServiceCareResult;
        
        public ServiceCareResponse() {
        }
        
        public ServiceCareResponse(NHS111.Integration.DOS.Api.DOSService.ServiceCareItem ServiceCareResult) {
            this.ServiceCareResult = ServiceCareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExceptionCapture", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ExceptionCaptureRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        public ExceptionCaptureRequest() {
        }
        
        public ExceptionCaptureRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExceptionCaptureResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ExceptionCaptureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.ExceptionCapture[] ExceptionCaptureResult;
        
        public ExceptionCaptureResponse() {
        }
        
        public ExceptionCaptureResponse(NHS111.Integration.DOS.Api.DOSService.ExceptionCapture[] ExceptionCaptureResult) {
            this.ExceptionCaptureResult = ExceptionCaptureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceCareException", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceCareExceptionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareException serviceCareExp;
        
        public ServiceCareExceptionRequest() {
        }
        
        public ServiceCareExceptionRequest(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.ServiceCareException serviceCareExp) {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.serviceCareExp = serviceCareExp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceCareExceptionResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceCareExceptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public string ServiceCareExceptionResult;
        
        public ServiceCareExceptionResponse() {
        }
        
        public ServiceCareExceptionResponse(string ServiceCareExceptionResult) {
            this.ServiceCareExceptionResult = ServiceCareExceptionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PathWayServiceSoapChannel : NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PathWayServiceSoapClient : System.ServiceModel.ClientBase<NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap>, NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap {
        
        public PathWayServiceSoapClient() {
        }
        
        public PathWayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PathWayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathWayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathWayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceDetailsById(NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest request) {
            return base.Channel.ServiceDetailsById(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.ContactDetail[] ServiceDetailsById(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, string serviceId) {
            NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceId = serviceId;
            NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceDetailsById(inValue);
            return retVal.ContactDetails;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceDetailsByIdAsync(NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest request) {
            return base.Channel.ServiceDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdResponse> ServiceDetailsByIdAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, string serviceId) {
            NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceDetailsByIdRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceId = serviceId;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.DispositionsResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.Dispositions(NHS111.Integration.DOS.Api.DOSService.DispositionsRequest request) {
            return base.Channel.Dispositions(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.Disposition[] Dispositions(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            NHS111.Integration.DOS.Api.DOSService.DispositionsRequest inValue = new NHS111.Integration.DOS.Api.DOSService.DispositionsRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            NHS111.Integration.DOS.Api.DOSService.DispositionsResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).Dispositions(inValue);
            return retVal.DispositionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.DispositionsResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.DispositionsAsync(NHS111.Integration.DOS.Api.DOSService.DispositionsRequest request) {
            return base.Channel.DispositionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.DispositionsResponse> DispositionsAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            NHS111.Integration.DOS.Api.DOSService.DispositionsRequest inValue = new NHS111.Integration.DOS.Api.DOSService.DispositionsRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).DispositionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.CheckCapacity(NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest request) {
            return base.Channel.CheckCapacity(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareDestination[] CheckCapacity(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest inValue = new NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.c = c;
            NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).CheckCapacity(inValue);
            return retVal.CheckCapacityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.CheckCapacityAsync(NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest request) {
            return base.Channel.CheckCapacityAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacityResponse> CheckCapacityAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest inValue = new NHS111.Integration.DOS.Api.DOSService.CheckCapacityRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.c = c;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).CheckCapacityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.CheckCapacitySummary(NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest request) {
            return base.Channel.CheckCapacitySummary(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareSummaryDestination[] CheckCapacitySummary(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest inValue = new NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.c = c;
            NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).CheckCapacitySummary(inValue);
            return retVal.CheckCapacitySummaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.CheckCapacitySummaryAsync(NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest request) {
            return base.Channel.CheckCapacitySummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryResponse> CheckCapacitySummaryAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.Case c) {
            NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest inValue = new NHS111.Integration.DOS.Api.DOSService.CheckCapacitySummaryRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.c = c;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).CheckCapacitySummaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceCare(NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest request) {
            return base.Channel.ServiceCare(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.ServiceCareItem ServiceCare(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, int serviceCareId) {
            NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceCareId = serviceCareId;
            NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceCare(inValue);
            return retVal.ServiceCareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceCareAsync(NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest request) {
            return base.Channel.ServiceCareAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareResponse> ServiceCareAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, int serviceCareId) {
            NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceCareRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceCareId = serviceCareId;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceCareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ExceptionCapture(NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest request) {
            return base.Channel.ExceptionCapture(request);
        }
        
        public NHS111.Integration.DOS.Api.DOSService.ExceptionCapture[] ExceptionCapture(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ExceptionCapture(inValue);
            return retVal.ExceptionCaptureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ExceptionCaptureAsync(NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest request) {
            return base.Channel.ExceptionCaptureAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureResponse> ExceptionCaptureAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo) {
            NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ExceptionCaptureRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ExceptionCaptureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceCareException(NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest request) {
            return base.Channel.ServiceCareException(request);
        }
        
        public string ServiceCareException(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.ServiceCareException serviceCareExp) {
            NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceCareExp = serviceCareExp;
            NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse retVal = ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceCareException(inValue);
            return retVal.ServiceCareExceptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse> NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap.ServiceCareExceptionAsync(NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest request) {
            return base.Channel.ServiceCareExceptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionResponse> ServiceCareExceptionAsync(string serviceVersion, NHS111.Integration.DOS.Api.DOSService.UserInfo userInfo, NHS111.Integration.DOS.Api.DOSService.ServiceCareException serviceCareExp) {
            NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest inValue = new NHS111.Integration.DOS.Api.DOSService.ServiceCareExceptionRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceCareExp = serviceCareExp;
            return ((NHS111.Integration.DOS.Api.DOSService.PathWayServiceSoap)(this)).ServiceCareExceptionAsync(inValue);
        }
    }
}
